eval "$(starship init zsh)"

source ~/.zprofile
source ~/dev/dotfiles/zsh/env.zsh
source ~/dev/dotfiles/zsh/functions.zsh
source ~/dev/dotfiles/zsh/mappings.zsh
source ~/dev/dotfiles/zsh/plugins.zsh
source ~/dev/dotfiles/zsh/fzf.zsh
source ~/dev/dotfiles/zsh/aliases.zsh
source ~/dev/dotfiles/zsh/completion.zsh

#turn on proxy
if [[ $MY_PROXY == http* ]]; then
      all_proxy_on
fi

# >>> xmake >>>
[[ -s "$HOME/.xmake/profile" ]] && source "$HOME/.xmake/profile" # load xmake profile
# <<< xmake <<<
